### ISSUE TITLE
How can I contact you?

### ISSUE THREAD

**Issue by guzmancarlosal** [phuctm97/phuctm97.com#467]
Hello, 
My name is Carlos Guzman.
I am required to develop Twitter/Notion Collaboration Tool.
While I am setting up the dev environment on my local, it asks me to ask you something.

![image](https://user-images.githubusercontent.com/17786145/236893663-16497f50-33fb-4f10-8ac7-7a5386e67424.png)
it is for extension.

![image](https://user-images.githubusercontent.com/17786145/236893762-8908d81f-1fcf-46f5-968a-8184b6b2868e.png)
it is for web.

![image](https://user-images.githubusercontent.com/17786145/236894731-736f72d6-bb12-4cf7-b10b-5def284f6c30.png)
It is for desktop.

Please let me know as soon as possible you can.
Thank you,
Carlos

**Comment by guzmancarlosal** [comment]
@phuctm97 I am waiting your replying.

**Comment by phuctm97** [comment]
Hi, for `web`, please follow the instruction to get environment variables from Vercel. To know which Vercel project to link to, please open the Vercel account that Queue is being deployed to (I have no access to at the moment, the new owner has), there should be either `queue-so` or `queue-web` project, please use those.

This should be enough for you to run `web` locally.

**Comment by guzmancarlosal** [comment]
@phuctm97 
![image](https://user-images.githubusercontent.com/17786145/236976154-9520479b-e077-4f17-ae15-5804c5c41e2c.png)
I just signed up with my github account. and I can see this.
Should I ask to import one of these 2 or should I ask my client to add me to the repo?

**Comment by guzmancarlosal** [comment]
@phuctm97 
![image](https://user-images.githubusercontent.com/17786145/236976442-b2b363f5-80cd-4a28-b66e-d6eced66eea0.png)
one more thing, it is very simple instruction. do you have the detailed instructions?

**Comment by phuctm97** [comment]
> @phuctm97 ![image](https://user-images.githubusercontent.com/17786145/236976154-9520479b-e077-4f17-ae15-5804c5c41e2c.png) I just signed up with my github account. and I can see this. Should I ask to import one of these 2 or should I ask my client to add me to the repo?

Please ask Queue's current owner to add you to their Vercel account, the Vercel project is in their account, not yours.

**Comment by guzmancarlosal** [comment]
@phuctm97 
It is working for web and desktop. I will close this issue.
